//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.12.18 at 03:30:23 PM CAT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.hit.ac.zw/ise7106/lab7", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package zw.ac.hit.ise7106.lab7;
